#!/bin/bash

# Exit if not at least one argument (the text of the filename)
if [ "$#" -lt 1 ]; then
	echo Nothing deleted: no task name given.
	exit 1
fi

# Put all command args into FILENAME
FILENAME="$*"

# Call wren, remove the arrows, grep for matches
MATCHES=$(wren | sed 's/➜ //g' | grep "$FILENAME")

if [ "${MATCHES}" == "" ]; then
	echo Nothing deleted: no MATCHES.
	exit 1
fi

# Check if there are any matches
NUM_MATCHES=$(echo "$MATCHES" | wc -l)

if [ "$NUM_MATCHES" -eq 0 ]; then
	echo Nothing deleted: no MATCHES.
	exit 1
elif [ "$NUM_MATCHES" -eq 1 ]; then
	# One match, delete it
	wren -d "$FILENAME"
else
	# More than one match, use zenity to select one
	MATCH=$(echo "$MATCHES" | zenity --list --text="Select a match" --column="Matches" --width=400 --height=300 2>/dev/null)

	# Check if a match was selected
	if [ -n "$MATCH" ]; then
		wren -d "$MATCH"
	else
		echo Nothing deleted: no match selected.
		exit 1
	fi
fi
